### ISSUE TITLE
amqp091 crashes in case of error

### ISSUE THREAD

**Issue by kire321** [lab-coop/lab-queue#1]
```
2017-02-23T14:41:09.589099444Z info: Error while processing queue item. Error: undefined
2017-02-23T14:41:09.591587525Z error:  TypeError: errorLogger is not a function
2017-02-23T14:41:09.591602024Z     at _callee$ (/var/app/node_modules/lab-queue/implementations/amqp091/message.js:47:15)
2017-02-23T14:41:09.591607524Z     at tryCatch (/var/app/node_modules/regenerator-runtime/runtime.js:64:40)
2017-02-23T14:41:09.591611024Z     at Generator.invoke [as _invoke] (/var/app/node_modules/regenerator-runtime/runtime.js:299:22)
2017-02-23T14:41:09.591614024Z     at step (/var/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
2017-02-23T14:41:09.591616923Z     at /var/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
```

/var/app/node_modules/lab-queue/implementations/amqp091/message.js:47 is supposed to pass 4 arguments, but it only passes 3.

**Comment by dsdenes** [comment]
https://github.com/lab-coop/lab-queue/commit/9e205ac70d8f5267d66788783437a139a52c0fc4
